stages:
  - test

Tests:
  stage: test
  rules:
#    - if: $CI_PIPELINE_SOURCE == 'schedule'
   - if: $CI_COMMIT_BRANCH == "psij-gitlab-integration"
  parallel:
    matrix:
      - HOST : [ "quartz", "ruby"]
        # LLNL_SLURM_SCHEDULER_PARAMETERS: --nodes=2 -t 60 -A exaworks_nightly_tests
        RUNNER_TYPE: "shell"
      - HOST : [ "lassen" ]
        # LLNL_LSF_SCHEDULER_PARAMETERS: [ "-nnodes 1 -W 60" ]
        ENVIRONMENT: [ "BATCH" ]
        RUNNER_TYPE: "batch"
  tags:
   - $HOST
   - $RUNNER_TYPE
  script:
   - mkdir psij-python3-venv
   - python3 -m venv psij-python3-venv
   - cd psij-python3-venv
   - source bin/activate
   - git clone git@github.com:ExaWorks/psij-python.git 
   - cd psij-python/
   - pip install --upgrade pip
   - pip install -r requirements-tests.txt
   - pip install -e . 
   - make tests
   - host="\"$HOST.llnl.gov/g\""
   - sed -i 's/maintainer_email =/maintainer_email = arambula2@llnl.gov/g' testing.conf
   - sed -i "s/id = hostname/id = \"$HOST.llnl.gov\"/g" testing.conf
   - sed -i "s/key = random/key = \"$SITE_KEY\"/g" testing.conf
   - pwd
   - ls -la
   - ls -la htmlcov
   # uncomment below to enable minimal uploads
   - sed -i "s/minimal_uploads = false/minimal_uploads = true/g" testing.conf
   - ./psij-ci-run

  artifacts: 
     name: "$CI_JOB_NAME_$HOST"
     paths:
       - $CI_PROJECT_DIR/psij-python3-venv/psij-python/htmlcov
